// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace KimonoMac
{
	public partial class WelcomeWindowController : NSWindowController
	{
		public WelcomeWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
